    ope-redis:
        build: ./ope-redis
        image: ope-redis
        ports:
            - "6379"
        volumes:
            - ./volumes/redis/data:/data:rw
        depends_on:
            - ope-gateway
            - ope-dns

